---
name: Deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.7]

    steps:
      - name: Create builder
        run: docker buildx create --use --name build --node build --driver-opt network=host
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Deploy image
        run: make deploy
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
